Lz15-17/Movies/Models/Purchase.cs
namespace Movies.Models
{
    public class Purchase
    {
        // ID покупки
        public int PurchaseId { get; set; }
        // ім'я й прізвище покупця
        public string Person { get; set; }
        // адреса покупця
        public string Address { get; set; }
        // ID книги
        public int TicketId { get; set; }
        // дата покупки
        public DateTime Date { get; set; }
    }
}

Lz15-17/Movies/Models/Ticket.cs
namespace Movies.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int SeatRow { get; set; }
        public int SeatNum { get; set; }

        public Session Session { get; set; }
    }
}

Lz15-17/Movies/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Models;
using Movies.Data;
using Microsoft.EntityFrameworkCore;

namespace Movies.Controllers
{
    public class SessionController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SessionController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var sessions = _db.Sessions
                .Include(s => s.Movie)
                .Include(s => s.Hall)
                .ToList();
            
            return View(sessions);
        }
        public IActionResult Create()
        {
            ViewBag.Movies = _db.Movies.ToList();
            ViewBag.Halls = _db.Halls.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Session session)
        {
            _db.Sessions.Add(session);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult MovieDetails(int id)
        {
            var movie = _db.Movies
                .Include(m => m.Genre)
                .Include(m => m.Sessions)
                .ThenInclude(s => s.Hall)
                .FirstOrDefault(x => x.Id == id);

            return View(movie);
        }
        public IActionResult CreateTicket(int id)
        {
            ViewBag.Session = _db.Sessions
                .Include(s => s.Movie)
                .Include(s => s.Hall)
                .FirstOrDefault(s => s.Id == id);

            return View();
        }
        [HttpPost]
        public IActionResult CreateTicket(Ticket ticket)
        {
            _db.Tickets.Add(ticket);
            _db.SaveChanges();

            return RedirectToAction("ShowTickets");
        }

        public IActionResult ShowTickets()
        {
            var tickets = _db.Tickets
                .Include(t => t.Session)
                .Include(t => t.Session.Movie)
                .Include(t => t.Session.Hall)
                .Include(t => t.Session.Movie.Genre)
                .ToList();

            return View(tickets);
        }

        [HttpGet]
        public IActionResult Buy(int? id)
        {
            ViewBag.Id = id ?? 0;
            return View();
        }
        [HttpPost]
        public IActionResult BuyResult(Purchase purchase)
        {
            ViewBag.Name = purchase.Person;
            purchase.Date = DateTime.Now;
            _db.Purchases.Add(purchase);
            _db.SaveChanges();
            return View();
        }
    }
}

Lz15-17/Movies/Views/Session/Buy.cshtml
@model Movies.Models.Purchase

@{
    ViewData["Title"] = "Buy";
}

<h1>Buy</h1>

<h4>Purchase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="BuyResult">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Person" class="control-label"></label>
                <input asp-for="Person" class="form-control" />
                <span asp-validation-for="Person" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <input asp-for="TicketId" type="hidden" value="@ViewBag.Id"/>
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowTickets">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lz15-17/Movies/Views/Session/CreateTicket.cshtml
@model Movies.Models.Ticket

@{
    ViewData["Title"] = "Create Ticket";
}

<h1>Create a ticket</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Session/CreateTicket" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input name="SessionId" value="@ViewBag.Session.Id" hidden />
            </div>
            <div class="form-group">
                <label asp-for="SeatRow" class="control-label">Row</label>
                <select asp-for="SeatRow" class="form-control">
                    @for(int i=1; i <= ViewBag.Session.Hall.Rows; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <span asp-validation-for="SeatRow" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeatNum" class="control-label">Seat</label>
                <select asp-for="SeatNum" class="form-control">
                    @for (int i=1; i <= ViewBag.Session.Hall.SeatsPerRow; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <span asp-validation-for="SeatNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Lz15-17/Movies/Views/Session/Index.cshtml
@model IEnumerable<Movies.Models.Session>

@{
    ViewData["Title"] = "Sessions";
}

<h1>Sessions</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
		<tr>
			<th>
				Movie
			</th>
            <th>
                Time and Date
            </th>
            <th>
                Hall
            </th>
            <th>
                Price
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a href="/Session/MovieDetails/@item.Movie.Id">@item.Movie.Title</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeDate)
            </td>
            <td>
                @item.Hall.Number
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a href="/Session/CreateTicket/@item.Id"><button>Pick a seat</button></a>
            </td>
        </tr>
}
    </tbody>
</table>

Lz15-17/Movies/Views/Session/MovieDetails.cshtml
@model Movies.Models.Movie

@{
    ViewData["Title"] = "Movie Details";
}

<h1>@Model.Title</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<br />
<br />
<div>
    <h4>Availible sessions:</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Time and Date
                </th>
                <th>
                    Hall
                </th>
                <th>
                    Price
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Sessions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeDate)
                    </td>
                    <td>
                        @item.Hall.Number
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a href="/Session/CreateTicket/@item.Id"><button>Pick a seat</button></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Lz15-17/Movies/Views/Session/ShowTickets.cshtml
@model IEnumerable<Movies.Models.Ticket>

@{
    ViewData["Title"] = "Tickets";
}

<h1>Tickets</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Movie
            </th>
            <th>
                Date and time
            </th>
            <th>
                Row
            </th>
            <th>
                Seat
            </th>
            <th>
                Hall
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a href="/Session/MovieDetails/@item.Session.Movie.Id">@item.Session.Movie.Title</a> 
            </td>
            <td>
                @item.Session.TimeDate
            </td>
            <td>
                @item.SeatRow
            </td>
            <td>
                @item.SeatNum
            </td>
            <td>
                @item.Session.Hall.Number
            </td>
            <td>
                @item.Session.Price
            </td>
            <td>
                <a href="/Session/Buy/@item.Id"><button class="btn btn-primary">Buy</button></a>
            </td>
        </tr>
}
    </tbody>
</table>

Lz15-17/Movies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movies.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Index">Sessions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="ShowTickets">Tickets</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Movies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>